### ISSUE TITLE
How to make the windows privoxy

### ISSUE THREAD

**Issue by K1GP** [ler762/privoxy#1]
Hi, Lee.
I'm trying to make the windows version with gui working but I know nothing about coding or mingGW.
I've got some error and warning when make it so I simply google the error code then C&P.
add #include <limits.h> in gateway.c
add #define _RICHEDIT_VER 0x0100 in w32log.c
But the final 'privoxy.exe' crash when I start it.
Is there something wrong or missing?
Thanks.

**Comment by ler762** [comment]
On 12/13/18, K1GP <notifications@github.com> wrote:
> Hi, Lee.

Hello

> I'm trying to make the windows version with gui working

I don't keep my github stuff current so I'd recommend getting the
source code from www.privoxy.org

> but I know nothing about coding or mingGW.

Not a problem - the docs take you step-by-step thru the process, so
you don't need to know anything about coding or mingw.   I'd
appreciate any feedback on how the docs could be improved - just send
it to the privoxy users list (privoxy-users@lists.privoxy.org)

> I've got some error and warning when make it so I simply google the error
> code then C&P.
> add #include <limits.h> in gateway.c
> add #define _RICHEDIT_VER 0x0100 in w32log.c
> But the final 'privoxy.exe' crash when I start it.

which is not all that surprising if you had to change anything..

The reason I put my copy of privoxy on github was to share the current
documentation.  It sounds like you've already got the docs, so open
 privoxy/doc/webserver/user-manual/index.html
click on the 'Windows' link under '2.2. Building from Source' and
follow the instructions

Real quick, it's
 install cygwin + support programs
 git clone https://www.privoxy.org/git/privoxy.git
     - which you might need to do in cygwin.  bash really doesn't like
dos line endings
 windows/MYconfigure && make
and you should have the windows gui version of privoxy that works

If you want to build the whole thing & not just privoxy.exe look at
the "Releasing a New Version" section of the developer manual.  But
probably
  cd windows
  make
is all you need to do if you're not changing anything.

Regards,
Lee

**Comment by K1GP** [comment]
Just like you said all I need to do is followed the docs step by step.
only the '**docbook-dssl**' part take me a few seconds.
there's only "**docbook-dsssl**" in the text list.
now I get a full working privoxy.exe.
Many thanks to you.

Regards,
K1GP

**Comment by ler762** [comment]
I'm glad to know you've got a working privoxy.exe :)

If you have any questions or need help with privoxy, there's a user and developer mailing list that gets you in contact with more than just me:
https://lists.privoxy.org/mailman/listinfo/
